---
- name: Install pip
  become: True
  ansible.builtin.apt:
    name: python3-pip

- name: Install requirements
  become: True
  ansible.builtin.pip:
    name: PyMySQL

- name: Install mariadb
  become: True
  ansible.builtin.apt:
    name: mariadb-server
  notify:
  - Restart mariadb

- name: Enable mariadb service
  become: True
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: True

- name: Add 0.0.0.0 to bind address
  become: true
  ansible.builtin.blockinfile:
    path: /etc/mysql/my.cnf
    block: |
      [mysqld]
      bind-address = 0.0.0.0
  notify:
  - Restart mariadb

- name: Create initial root user
  become: true
  community.mysql.mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    login_unix_socket: /run/mysqld/mysqld.sock
    login_password: "{{ mariadb_root_password }}"
  notify:
  - Restart mariadb

- name: Create database test
  become: true
  community.mysql.mysql_db:
    name: test
    state: present
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  notify:
  - Restart mariadb

