---
all:
  hosts:
    webserver:
      ansible_user: ubuntu
      ansible_host: 15.188.27.195
      ansible_ssh_private_key_file: ./key-aws.pem
    database:
      ansible_user: ubuntu
      ansible_host: 10.12.2.82
      ansible_ssh_private_key_file: ./key-aws.pem
      ansible_ssh_common_args: '-o ProxyCommand="ssh -i key-aws.pem -W %h:%p -q ubuntu@15.188.27.195"'
  children:
    webserver:
      hosts:
        webserver: {}
    database:
      hosts:
        database: {}