- name: Install apache
  become: True
  ansible.builtin.apt:
    name: apache2
  notify:
  - Restart apache

- name: Enable apache service
  become: True
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: True
    
- name: Install php
  become: True
  ansible.builtin.apt:
    name:
    - php8.1
    - libapache2-mod-php8.1
    - php-mysql
  notify:
  - Restart apache
